import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Heart,MessageCircle,BookOpen,Users,Shield,LifeBuoy,BarChart3,Send}from'lucide-react';import'./styles.css';
const uid=()=>localStorage.getItem('qc_user')||(()=>{const id='user_'+Math.random().toString(36).slice(2);localStorage.setItem('qc_user',id);return id})()
const store=(k,d=null)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function App(){const[page,setPage]=useState('home');const[user,setUser]=useState(()=>store('profile',{id:uid(),name:'Quiet Soul',language:'english',persona:'supportive_friend'}));const[moods,setMoods]=useState(()=>store('moods',[]));const[journals,setJournals]=useState(()=>store('journals',[]));const[msgs,setMsgs]=useState(()=>store('msgs',[{room:'2am_thoughts',name:'System',text:'Welcome. Be kind, anonymous, and respectful.'}]));const[reports,setReports]=useState(()=>store('reports',[]));useEffect(()=>save('profile',user),[user]);useEffect(()=>save('moods',moods),[moods]);useEffect(()=>save('journals',journals),[journals]);useEffect(()=>save('msgs',msgs),[msgs]);useEffect(()=>save('reports',reports),[reports]);return <div><Header page={page} setPage={setPage}/><main>{page==='home'&&<Home setPage={setPage} moods={moods} journals={journals} reports={reports}/>} {page==='mood'&&<Mood add={m=>setMoods([{...m,date:new Date().toLocaleString()},...moods])}/>} {page==='journal'&&<Journal journals={journals} add={j=>setJournals([{...j,date:new Date().toLocaleString()},...journals])}/>} {page==='companion'&&<Companion/>} {page==='rooms'&&<Rooms msgs={msgs} addMsg={m=>setMsgs([...msgs,m])} report={r=>setReports([{...r,status:'pending',date:new Date().toLocaleString()},...reports])}/>} {page==='crisis'&&<Crisis/>} {page==='profile'&&<Profile user={user} setUser={setUser}/>} {page==='admin'&&<Admin reports={reports} msgs={msgs}/>}</main></div>}
function Header({page,setPage}){const nav=[['home','Dashboard',Heart],['mood','Mood',BarChart3],['journal','Journal',BookOpen],['companion','AI Companion',MessageCircle],['rooms','Rooms',Users],['crisis','Help',LifeBuoy],['profile','Profile',Shield],['admin','Admin',Shield]];return <header><div className="brand">Quiet Circle</div><nav>{nav.map(([id,t,I])=><button className={page===id?'active':''} onClick={()=>setPage(id)}><I size={16}/>{t}</button>)}</nav></header>}
function Home({setPage,moods,journals,reports}){return <section className="hero"><div><p className="pill">Anonymous emotional support space</p><h1>A safe place to pause, reflect, and feel heard.</h1><p>Track your mood, write privately, join kind rooms, and get supportive AI-guided prompts.</p><button onClick={()=>setPage('mood')}>Start check-in</button><button className="ghost" onClick={()=>setPage('companion')}>Talk to companion</button></div><div className="grid"><Card title="Mood logs" value={moods.length}/><Card title="Journal entries" value={journals.length}/><Card title="Open reports" value={reports.filter(r=>r.status==='pending').length}/><Card title="Safety" value="On"/></div></section>}
function Card(p){return <div className="card"><small>{p.title}</small><h2>{p.value}</h2></div>}
function Mood({add}){const[score,setScore]=useState(5),[note,setNote]=useState('');return <section className="panel"><h1>Mood Check-in</h1><p>How are you feeling today?</p><input type="range" min="1" max="10" value={score} onChange={e=>setScore(e.target.value)}/><h2>{score}/10</h2><textarea placeholder="Optional note" value={note} onChange={e=>setNote(e.target.value)}/><button onClick={()=>{add({score,note});setNote('')}}>Save mood</button></section>}
function Journal({journals,add}){const[content,setContent]=useState('');return <section className="panel"><h1>Private Journal</h1><textarea placeholder="Write what you cannot say out loud..." value={content} onChange={e=>setContent(e.target.value)}/><button onClick={()=>{if(content.trim()){add({content});setContent('')}}}>Save privately</button><div>{journals.map((j,i)=><div className="item" key={i}><small>{j.date}</small><p>{j.content}</p></div>)}</div></section>}
function Companion(){const[chat,setChat]=useState([{from:'ai',text:'I’m here with you. What feels heavy right now?'}]);const[text,setText]=useState('');function send(){if(!text.trim())return;const crisis=/suicide|kill myself|self harm|die/i.test(text);setChat([...chat,{from:'me',text},{from:'ai',text:crisis?'I’m really sorry you’re feeling this. Please contact emergency services or a crisis hotline now. You deserve immediate support.':'Thank you for sharing. Take one slow breath. What is one small thing that would make the next 10 minutes easier?'}]);setText('')}return <section className="panel"><h1>AI Companion</h1><div className="chat">{chat.map((m,i)=><p className={m.from} key={i}>{m.text}</p>)}</div><div className="row"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Type here..."/><button onClick={send}><Send size={16}/></button></div><small>Not medical advice. If you are in danger, contact emergency services.</small></section>}
function Rooms({msgs,addMsg,report}){const[text,setText]=useState('');const room='2am_thoughts';return <section className="panel"><h1>2 AM Thoughts Room</h1><p>Anonymous group space. Keep it kind.</p><div className="chat">{msgs.filter(m=>m.room===room).map((m,i)=><div className="item"><b>{m.name}</b><p>{m.text}</p><button className="link" onClick={()=>report({message:m.text,reason:'unsafe_or_harmful'})}>Report</button></div>)}</div><div className="row"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Share gently..."/><button onClick={()=>{if(text.trim()){addMsg({room,name:'Anonymous',text});setText('')}}}>Post</button></div></section>}
function Crisis(){return <section className="panel"><h1>Crisis Resources</h1><div className="item"><b>Emergency</b><p>If you are in immediate danger, call local emergency services now.</p></div><div className="item"><b>988 Lifeline</b><p>US/Canada: Call or text 988 for crisis support.</p></div><div className="item"><b>India Emergency</b><p>Call 112 for emergency help in India.</p></div></section>}
function Profile({user,setUser}){return <section className="panel"><h1>Profile</h1><input value={user.name} onChange={e=>setUser({...user,name:e.target.value})}/><select value={user.persona} onChange={e=>setUser({...user,persona:e.target.value})}><option>supportive_friend</option><option>calm_listener</option><option>motivator</option><option>wise_elder</option></select><p>Anonymous ID: {user.id}</p></section>}
function Admin({reports,msgs}){return <section className="panel"><h1>Admin Moderation</h1><Card title="Total messages" value={msgs.length}/><Card title="Reports" value={reports.length}/>{reports.map((r,i)=><div className="item"><b>{r.reason}</b><p>{r.message}</p><small>{r.date}</small></div>)}</section>}
createRoot(document.getElementById('root')).render(<App/>);
